version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./gradlew assemble
      - run: ./gradlew check
  copilot:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - run: bash <(curl -s https://copilot-valid.blackducksoftware.com/ci/circle/scripts/upload)
workflows:
  version: 2
  build-and-scan:
    jobs:
      - build
      - copilot:
          requires:
            - build
